# Generated by Django 6.0.3 on 2026-04-02 02:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode_wilayah', models.CharField(max_length=20, unique=True)),
                ('nama_kecamatan', models.CharField(max_length=100)),
                ('nama_kelurahan', models.CharField(max_length=100)),
                ('target_usaha', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wilayah',
                'verbose_name_plural': 'Data Wilayah',
            },
        ),
    ]
