# Generated by Django 6.0.3 on 2026-06-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wilayah',
            options={},
        ),
        migrations.RemoveField(
            model_name='wilayah',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wilayah',
            name='kode_wilayah',
        ),
        migrations.AddField(
            model_name='wilayah',
            name='kode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
