# Generated by Django 6.0.3 on 2026-04-02 02:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensusEkonomi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tahun_sensus', models.CharField(max_length=4)),
                ('nama_sensus', models.CharField(max_length=200)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(choices=[('persiapan', 'Persiapan'), ('berjalan', 'Sedang Berjalan'), ('selesai', 'Selesai')], default='persiapan', max_length=20)),
                ('deskripsi', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sensus Ekonomi',
                'verbose_name_plural': 'Data Sensus Ekonomi',
            },
        ),
    ]
