# Generated by Django 6.0.3 on 2026-04-02 02:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('no_hp', models.CharField(max_length=15)),
                ('status_aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petugas',
                'verbose_name_plural': 'Data Petugas',
            },
        ),
        migrations.CreateModel(
            name='ProgresHarian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal_laporan', models.DateField()),
                ('jumlah_selesai', models.IntegerField(default=0)),
                ('jumlah_bermasalah', models.IntegerField(default=0)),
                ('catatan', models.TextField(blank=True)),
                ('status_validasi', models.CharField(choices=[('menunggu', 'Menunggu Validasi'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progres.petugas')),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progres Harian',
                'verbose_name_plural': 'Data Progres Harian',
            },
        ),
        migrations.CreateModel(
            name='Kendala',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jenis_kendala', models.CharField(choices=[('tidak_ditemukan', 'Usaha Tidak Ditemukan'), ('menolak', 'Pemilik Menolak'), ('alamat_salah', 'Alamat Tidak Sesuai'), ('tutup', 'Usaha Sudah Tutup'), ('akses_jalan', 'Akses Jalan Sulit'), ('cuaca', 'Kendala Cuaca'), ('lainnya', 'Lainnya')], max_length=50)),
                ('deskripsi', models.TextField()),
                ('status_penanganan', models.CharField(choices=[('belum', 'Belum Ditangani'), ('proses', 'Sedang Diproses'), ('selesai', 'Sudah Diselesaikan')], default='belum', max_length=20)),
                ('solusi', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('progres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progres.progresharian')),
            ],
            options={
                'verbose_name': 'Kendala',
                'verbose_name_plural': 'Data Kendala',
            },
        ),
    ]
