# Generated by Django 6.0.3 on 2026-04-10 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progres', '0001_initial'),
        ('wilayah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresharian',
            name='wilayah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.wilayah'),
        ),
    ]
